### ISSUE TITLE
Strange error now

### ISSUE THREAD

**Issue by westfield-ben** [jaroslawhartman/withings-garmin-v2#7] opened 2018-04-01 18:38 UTC
Thanks for updating repo.  Getting strange error now:

 File "sync.py", line 77
    print 'could not find user: %s' % withings_shortname
                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print 'could not find user: %s' % withings_shortname)?

**Comment by jaroslawhartman** [comment] 2018-04-02 13:56
Trying to reproduce but somehow can't ... perhaps it's because your account has been set at some point of time as non-pubic?

Thank you,
Jarek

**Comment by agentbond007** [comment] 2018-04-02 23:41
Thanks.  Nothing has changed except that Withings.com is now Nokia.  How do
you ensure  is public?

Here's the string I'm using.

python sync.py -f 2017-04-04 -t 2017-08-08 --wu benmorris@gmail.com --wp
xxxxx --ws BEN --gu benmorris@gmail.com --gp xxxxx

Thank you for any clues.

**Comment by magikid** [comment] 2018-04-04 19:37
I think this is related to your version of python.  Python 2 doesn't require parentheses around print statements but Python 3 does.  For example:

Python2:
```python
print "Hello world"
```

Python3:
```python
print("Hello world")
```

What version of Python are you using?

**Comment by westfield-ben** [comment] 2018-04-05 04:36
You were right @magikid, however.  I confirmed Python 2.7 and then still received:
Traceback (most recent call last):
  File "sync.py", line 126, in <module>
    main()
  File "sync.py", line 59, in main
    sync(**opts.__dict__)
  File "sync.py", line 118, in sync
    session = garmin.login(garmin_username, garmin_password)
  File "/Users/bmorris/python-test/withings-garmin-v2/garmin.py", line 135, in login
    session = self._get_session(email=username, password=password)
  File "/Users/bmorris/python-test/withings-garmin-v2/garmin.py", line 96, in _get_session
    raise APIException("GC redeem-start error %s %s" % (gcRedeemResp.status_code, gcRedeemResp.text))
NameError: global name 'APIException' is not defined

**Comment by westfield-ben** [comment] 2018-04-06 00:47
generating fit file...
appending weight scale record... 2018-02-24 18:04:46 66.4kg 6.245%
appending weight scale record... 2018-02-23 08:24:28 65.35kg 7.503%
appending weight scale record... 2018-02-20 07:59:59 66.75kg 6.273%
appending weight scale record... 2018-02-18 13:22:19 65.65kg 6.129%
appending weight scale record... 2018-02-17 15:20:03 65.95kg 5.918%
appending weight scale record... 2018-02-14 09:07:50 65.85kg 6.336%
appending weight scale record... 2018-02-12 08:00:03 66.45kg 7.421%
appending weight scale record... 2018-02-10 14:47:06 65.4kg 5.606%
appending weight scale record... 2018-02-09 07:48:59 65.85kg 8.358%
appending weight scale record... 2018-02-07 08:49:28 65.7kg 8.793%
appending weight scale record... 2018-02-06 08:33:14 65.5kg 7.594%
appending weight scale record... 2018-02-03 15:18:55 63.9kg 7.261%
appending weight scale record... 2018-01-30 08:25:13 66.75kg 9.575%
appending weight scale record... 2018-01-27 14:53:55 65.8kg 7.857%
appending weight scale record... 2018-01-25 08:23:43 66.65kg 8.984%
appending weight scale record... 2018-01-20 15:44:37 66.5kg 7.402%
appending weight scale record... 2018-01-16 07:28:28 67.7kg 9.789%
appending weight scale record... 2018-01-11 08:57:42 66.75kg 6.548%
Traceback (most recent call last):
  File "sync.py", line 126, in <module>
    main()
  File "sync.py", line 59, in main
    sync(**opts.__dict__)
  File "sync.py", line 118, in sync
    session = garmin.login(garmin_username, garmin_password)
  File "/Users/bmorris/python-test/withings-garmin-v2/garmin.py", line 135, in login
    session = self._get_session(email=username, password=password)
  File "/Users/bmorris/python-test/withings-garmin-v2/garmin.py", line 96, in _get_session
    raise APIException("GC redeem-start error %s %s" % (gcRedeemResp.status_code, gcRedeemResp.text))
NameError: global name 'APIException' is not defined

**Comment by magnific0** [comment] 2018-04-09 14:57
@westfield-ben @jaroslawhartman 

Garmin changed stuff on their end. The fix is rather straight forward, see:

https://github.com/cpfair/tapiriik/commit/656bb2066f9b753c2e3e87a66bef38d21c21c63b

I use garmin.py in [my project nokia-weight-sync](https://github.com/magnific0/nokia-weight-sync). It borrows code from this project and several others. It's purpose is similar too, but uses the Nokia Health API instead of login. It also synchronizes to Smashrun.

**Comment by jaroslawhartman** [comment] 2018-04-09 15:00
Thanks @magnific0 ! I will take a look as well to get it merged.

**Comment by jaroslawhartman** [comment] 2018-04-11 17:45
Fixed issue pointed out by @magnific0 I will close this issue, compatibility with Python 3 will be tracked in #8.

Thank you and best regards,
Jarek

**Closed as completed by jaroslawhartman** 2018-04-11 17:45 UTC
